/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsHost: typeof import('./components/AlertsHost.vue')['default']
    ApplicationBar: typeof import('./components/dashboard/ApplicationBar.vue')['default']
    BottomNavigationBar: typeof import('./components/dashboard/BottomNavigationBar.vue')['default']
    CarInventory: typeof import('./components/inventory/CarInventory.vue')['default']
    CarInventoryListingItem: typeof import('./components/inventory/CarInventoryListingItem.vue')['default']
    DisplayObject: typeof import('./components/DisplayObject.vue')['default']
    Faq: typeof import('./components/home/Faq.vue')['default']
    FerrariCar: typeof import('./components/three/FerrariCar.vue')['default']
    FilterForm: typeof import('./components/FilterForm.vue')['default']
    HeaderBar: typeof import('./components/home/HeaderBar.vue')['default']
    HeroSection: typeof import('./components/home/HeroSection.vue')['default']
    HomePage: typeof import('./components/home/HomePage.vue')['default']
    LeftNavigationDrawer: typeof import('./components/dashboard/LeftNavigationDrawer.vue')['default']
    ListingFeedCard: typeof import('./components/home/ListingFeedCard.vue')['default']
    ListingsFeed: typeof import('./components/home/ListingsFeed.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    PFooter: typeof import('./components/PFooter.vue')['default']
    QuickCarTypes: typeof import('./components/home/QuickCarTypes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./components/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
    WhyChooseUs: typeof import('./components/home/WhyChooseUs.vue')['default']
  }
}
