/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsHost: typeof import('./components/AlertsHost.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApplicationBar: typeof import('./components/dashboard/ApplicationBar.vue')['default']
    BottomNavigationBar: typeof import('./components/dashboard/BottomNavigationBar.vue')['default']
    CarInventory: typeof import('./components/inventory/CarInventory.vue')['default']
    CarInventoryListingItem: typeof import('./components/inventory/CarInventoryListingItem.vue')['default']
    DisplayObject: typeof import('./components/DisplayObject.vue')['default']
    FilterForm: typeof import('./components/FilterForm.vue')['default']
    HeaderBar: typeof import('./components/home/HeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/home/HeroSection.vue')['default']
    HomePage: typeof import('./components/home/HomePage.vue')['default']
    LeftNavigationDrawer: typeof import('./components/dashboard/LeftNavigationDrawer.vue')['default']
    PetroletBox: typeof import('./components/tres/PetroletBox.vue')['default']
    QuickCarTypes: typeof import('./components/home/QuickCarTypes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperTest: typeof import('./components/SwiperTest.vue')['default']
    TresLab: typeof import('./components/TresLab.vue')['default']
    UgglyBunny: typeof import('./components/tres/UglyBunny.vue')['default']
    UglyBunny: typeof import('./components/tres/UglyBunny.vue')['default']
    WhyChooseUs: typeof import('./components/home/WhyChooseUs.vue')['default']
  }
}
